language: python
cache: # caching is only available for customers who pay
    directories:
        - $HOME/.cache/pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DEBUG_MEMENTO_CLIENT=1
script:
    - python setup.py test
    - python setup.py sdist bdist_wheel
branches:
    only:
        - master
